### ISSUE TITLE
HOW to solve this problem?

### ISSUE THREAD

**Issue by takeawayls** [qinjr/UBR4CTR#1]
Traceback (most recent call last):
  File "preprocess_taobao.py", line 197, in <module>
    insert_elastic(FEATENG_DIR + 'database.txt')
  File "preprocess_taobao.py", line 189, in insert_elastic
    writer.write()
  File "/UBR4CTR-master/code/elastic_client.py", line 70, in write
    elasticsearch.helpers.bulk(self.es, actions)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 390, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 320, in streaming_bulk
    **kwargs
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 247, in _process_bulk_chunk
    for item in gen:
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 196, in _process_bulk_chunk_error
    raise error
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 235, in _process_bulk_chunk
    resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 460, in bulk
    body=body,
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 316, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;7: type is missing;8: type is missing;9: type is missing;10: type is missing;11: type is missing;12: type is missing;13: type is missing;14: type is missing;15: type is missing;16: type is missing;17: type is missing;18: type is missing;19: type is missing;20: type is missing;21: type is missing;22: type is missing;23: type is missing;24: type is missing;25: type is missing;26: type is missing;27: type is missing;28: type is missing;29: type is missing;30: type is missing;31: type is missing;32: type is missing;33: type is missing;34: type is missing;35: type is missing;36: type is missing;37: type is missing;38: type is missing;39: type is missing;40: type is missing;41: type is missing;42: type is missing;43: type is missing;44: type is missing;45: type is missing;46: type is missing;47: type is missing;48: type is missing;49: type is missing;50: type is missing;51: type is missing;52: type is missing;53: type is missing;54: type is missing;55: type is missing;56: type is missing;57: type is missing;58: type is missing;59: type is missing;60: type is missing;61: type is missing;62: type is missing;63: type is missing;64: type is missing;65: type is missing;66: type is missing;67: type is missing;68: type is missing;69: type is missing;70: type is missing;71: type is missing;72: type is missing;73: type is missing;74: type is missing;75: type is missing;76: type is missing;77: type is missing;78: type is missing;79: type is missing;80: type is missing;81: type is missing;82: type is missing;83: type is missing;84: type is missing;85: type is missing;86: type is missing;87: type is missing;88: type is missing;89: type is missing;90: type is missing;91: type is missing;92: type is missing;93: type is missing;94: type is missing;95: type is missing;96: type is missing;97: type is missing;98: type is missing;99: type is missing;100: type is missing;101: type is missing;102: type is missing;103: type is missing;104: type is missing;105: type is missing;106: type is missing;107: type is missing;108: type is missing;109: type is missing;110: type is missing;111: type is missing;112: type is missing;113: type is missing;114: type is missing;115: type is missing;116: type is missing;117: type is missing;118: type is missing;119: type is missing;120: type is missing;121: type is missing;122: type is missing;123: type is missing;124: type is missing;125: type is missing;126: type is missing;127: type is missing;128: type is missing;129: type is missing;130: type is missing;131: type is missing;132: type is missing;133: type is missing;134: type is missing;135: type is missing;136: type is missing;137: type is missing;138: type is missing;139: type is missing;140: type is missing;141: type is missing;142: type is missing;143: type is missing;144: type is missing;145: type is missing;146: type is missing;147: type is missing;148: type is missing;149: type is missing;150: type is missing;151: type is missing;152: type is missing;153: type is missing;154: type is missing;155: type is missing;156: type is missing;157: type is missing;158: type is missing;159: type is missing;160: type is missing;161: type is missing;162: type is missing;163: type is missing;164: type is missing;165: type is missing;166: type is missing;167: type is missing;168: type is missing;169: type is missing;170: type is missing;171: type is missing;172: type is missing;173: type is missing;174: type is missing;175: type is missing;176: type is missing;177: type is missing;178: type is missing;179: type is missing;180: type is missing;181: type is missing;182: type is missing;183: type is missing;184: type is missing;185: type is missing;186: type is missing;187: type is missing;188: type is missing;189: type is missing;190: type is missing;191: type is missing;192: type is missing;193: type is missing;194: type is missing;195: type is missing;196: type is missing;197: type is missing;198: type is missing;199: type is missing;200: type is missing;201: type is missing;202: type is missing;203: type is missing;204: type is missing;205: type is missing;206: type is missing;207: type is missing;208: type is missing;209: type is missing;210: type is missing;211: type is missing;212: type is missing;213: type is missing;214: type is missing;215: type is missing;216: type is missing;217: type is missing;218: type is missing;219: type is missing;220: type is missing;221: type is missing;222: type is missing;223: type is missing;224: type is missing;225: type is missing;226: type is missing;227: type is missing;228: type is missing;229: type is missing;230: type is missing;231: type is missing;232: type is missing;233: type is missing;234: type is missing;235: type is missing;236: type is missing;237: type is missing;238: type is missing;239: type is missing;240: type is missing;241: type is missing;242: type is missing;243: type is missing;244: type is missing;245: type is missing;246: type is missing;247: type is missing;248: type is missing;249: type is missing;250: type is missing;251: type is missing;252: type is missing;253: type is missing;254: type is missing;255: type is missing;256: type is missing;257: type is missing;258: type is missing;259: type is missing;260: type is missing;261: type is missing;262: type is missing;263: type is missing;264: type is missing;265: type is missing;266: type is missing;267: type is missing;268: type is missing;269: type is missing;270: type is missing;271: type is missing;272: type is missing;273: type is missing;274: type is missing;275: type is missing;276: type is missing;277: type is missing;278: type is missing;279: type is missing;280: type is missing;281: type is missing;282: type is missing;283: type is missing;284: type is missing;285: type is missing;286: type is missing;287: type is missing;288: type is missing;289: type is missing;290: type is missing;291: type is missing;292: type is missing;293: type is missing;294: type is missing;295: type is missing;296: type is missing;297: type is missing;298: type is missing;299: type is missing;300: type is missing;301: type is missing;302: type is missing;303: type is missing;304: type is missing;305: type is missing;306: type is missing;307: type is missing;308: type is missing;309: type is missing;310: type is missing;311: type is missing;312: type is missing;313: type is missing;314: type is missing;315: type is missing;316: type is missing;317: type is missing;318: type is missing;319: type is missing;320: type is missing;321: type is missing;322: type is missing;323: type is missing;324: type is missing;325: type is missing;326: type is missing;327: type is missing;328: type is missing;329: type is missing;330: type is missing;331: type is missing;332: type is missing;333: type is missing;334: type is missing;335: type is missing;336: type is missing;337: type is missing;338: type is missing;339: type is missing;340: type is missing;341: type is missing;342: type is missing;343: type is missing;344: type is missing;345: type is missing;346: type is missing;347: type is missing;348: type is missing;349: type is missing;350: type is missing;351: type is missing;352: type is missing;353: type is missing;354: type is missing;355: type is missing;356: type is missing;357: type is missing;358: type is missing;359: type is missing;360: type is missing;361: type is missing;362: type is missing;363: type is missing;364: type is missing;365: type is missing;366: type is missing;367: type is missing;368: type is missing;369: type is missing;370: type is missing;371: type is missing;372: type is missing;373: type is missing;374: type is missing;375: type is missing;376: type is missing;377: type is missing;378: type is missing;379: type is missing;380: type is missing;381: type is missing;382: type is missing;383: type is missing;384: type is missing;385: type is missing;386: type is missing;387: type is missing;388: type is missing;389: type is missing;390: type is missing;391: type is missing;392: type is missing;393: type is missing;394: type is missing;395: type is missing;396: type is missing;397: type is missing;398: type is missing;399: type is missing;400: type is missing;401: type is missing;402: type is missing;403: type is missing;404: type is missing;405: type is missing;406: type is missing;407: type is missing;408: type is missing;409: type is missing;410: type is missing;411: type is missing;412: type is missing;413: type is missing;414: type is missing;415: type is missing;416: type is missing;417: type is missing;418: type is missing;419: type is missing;420: type is missing;421: type is missing;422: type is missing;423: type is missing;424: type is missing;425: type is missing;426: type is missing;427: type is missing;428: type is missing;429: type is missing;430: type is missing;431: type is missing;432: type is missing;433: type is missing;434: type is missing;435: type is missing;436: type is missing;437: type is missing;438: type is missing;439: type is missing;440: type is missing;441: type is missing;442: type is missing;443: type is missing;444: type is missing;445: type is missing;446: type is missing;447: type is missing;448: type is missing;449: type is missing;450: type is missing;451: type is missing;452: type is missing;453: type is missing;454: type is missing;455: type is missing;456: type is missing;457: type is missing;458: type is missing;459: type is missing;460: type is missing;461: type is missing;462: type is missing;463: type is missing;464: type is missing;465: type is missing;466: type is missing;467: type is missing;468: type is missing;469: type is missing;470: type is missing;471: type is missing;472: type is missing;473: type is missing;474: type is missing;475: type is missing;476: type is missing;477: type is missing;478: type is missing;479: type is missing;480: type is missing;481: type is missing;482: type is missing;483: type is missing;484: type is missing;485: type is missing;486: type is missing;487: type is missing;488: type is missing;489: type is missing;490: type is missing;491: type is missing;492: type is missing;493: type is missing;494: type is missing;495: type is missing;496: type is missing;497: type is missing;498: type is missing;499: type is missing;500: type is missing;')

**Comment by qinjr** [comment]
Sorry for the late response, it seems you are using an old version of ElasticSearch. 
I use the version 7.6.0.

**Comment by takeawayls** [comment]
thank you for your reply, I have found the problem is that I was not granted by the GPU platform, and I asked the technicians solve the problem.Anyway, the problem has solved, thank you.
