### ISSUE TITLE
preprocess_taobao.py文件运行无结果

### ISSUE THREAD

**Issue by zjjhuihui** [qinjr/UBR4CTR#2]
您好,请问一下我在运行preprocess_taobao.py文件时候只有id_remap_dict.pkl文件输出,没有remapped_log.csv、user_seq_dict.pkl、item_feat_dict.pkl等文件的输出,请问该如何解决呢?

**Comment by qinjr** [comment]
您好，收到您的邮件。为什么debug模式之后再运行就不对了？是不是还是有断点啊？只看你的邮件内容我不太清楚是怎么回事。而且remapped_log.csv、user_seq_dict.pkl、item_feat_dict.pkl只需要生成一次就可以了。
关于remapped_log.csv，它的意思是原始feature经过特征工程映射之后的log文件，user_seq_dict.pkl是uid为key，iid seq为value的dict，意思是每个用户的行为序列，item_feat_dict.pkl是iid对应的item features，key是iid，value是这个item的其他feature组成的list，taobao数据集里就是[category_id]。

**Comment by zjjhuihui** [comment]
您好:
        非常感谢作者您的及时回复,debug时候确实有设置断点,但后来断点取消重新运行后确实没生成remapped_log.csv、user_seq_dict.pkl、item_feat_dict.pkl等几个文件,
我当时debug是想看看生成这几个文件的程序在哪里,单纯一个preprocess_taobao.py按程序理解只会生成id_remap_dict.pkl文件,不明白为何会有其他几个文件的生成,当时也不明白为何会出来那么多文件,
现在我想恢复到最开始的状态想要生成包含remapped_log.csv、user_seq_dict.pkl、item_feat_dict.pkl等几个文件的结果,一直没成功,尝试了清除缓存、重启的方式,目前还是只能生成id_remap_dict.pkl文件,方便电话沟通么?我邮件发您我的联系方式.

**Comment by zjjhuihui** [comment]
> 您好，收到您的邮件。为什么debug模式之后再运行就不对了？是不是还是有断点啊？只看你的邮件内容我不太清楚是怎么回事。而且remapped_log.csv、user_seq_dict.pkl、item_feat_dict.pkl只需要生成一次就可以了。
> 关于remapped_log.csv，它的意思是原始feature经过特征工程映射之后的log文件，user_seq_dict.pkl是uid为key，iid seq为value的dict，意思是每个用户的行为序列，item_feat_dict.pkl是iid对应的item features，key是iid，value是这个item的其他feature组成的list，taobao数据集里就是[category_id]。

您好:
非常感谢作者您的及时回复,debug时候确实有设置断点,但后来断点取消重新运行后确实没生成remapped_log.csv、user_seq_dict.pkl、item_feat_dict.pkl等几个文件,
我当时debug是想看看生成这几个文件的程序在哪里,单纯一个preprocess_taobao.py按程序理解只会生成id_remap_dict.pkl文件,不明白为何会有其他几个文件的生成,当时也不明白为何会出来那么多文件,
现在我想恢复到最开始的状态想要生成包含remapped_log.csv、user_seq_dict.pkl、item_feat_dict.pkl等几个文件的结果,一直没成功,尝试了清除缓存、重启的方式,目前还是只能生成id_remap_dict.pkl文件,方便电话沟通么?我邮件发您我的联系方式.

**Comment by qinjr** [comment]
“单纯一个preprocess_taobao.py按程序理解只会生成id_remap_dict.pkl文件”为什么？
 remap_log_file这个函数就会生成那些文件呀？
如果你现在有id_remap_dict.pkl，那你就可以注释掉
`feateng(RAW_DIR + 'UserBehavior.csv', FEATENG_DIR + 'id_remap_dict.pkl')`
这一行，直接从remap_log_file开始运行

**Comment by zjjhuihui** [comment]
> “单纯一个preprocess_taobao.py按程序理解只会生成id_remap_dict.pkl文件”为什么？
> remap_log_file这个函数就会生成那些文件呀？
> 如果你现在有id_remap_dict.pkl，那你就可以注释掉
> `feateng(RAW_DIR + 'UserBehavior.csv', FEATENG_DIR + 'id_remap_dict.pkl')`
> 这一行，直接从remap_log_file开始运行

谢谢答复,我懂了,我注释了feateng后的所有内容导致的问题,谢谢答复.

**Comment by zjjhuihui** [comment]
请问模型中淘宝数据集FEAT_SIZE_TAOBAO = 5062314,dataset_size = 1962046这两个参数为何分别设置为这两个值呢?git中给出的数据集长度是5000,dataset_size不应该是5000么?
