### ISSUE TITLE
论文代码细节咨询

### ISSUE THREAD

**Issue by Jhin3433** [qinjr/UBR4CTR#4]
请问在feature进行embedding初始化的时候，为什么要把embedding matrix的首行设置为全0呢？self.emb_mtx_mask使得self.emb_mtx的首行全变为了0，这样不就导致缺少了一个feature的embedding？
![image](https://user-images.githubusercontent.com/33836571/124573609-4af7d900-de7c-11eb-916c-957dfc2975cf.png)

**Comment by qinjr** [comment]
0用于表示padding，其他有意义的feature id是从1开始的

**Comment by Jhin3433** [comment]
![image](https://user-images.githubusercontent.com/33836571/126424591-d0709bf2-3288-42a3-884d-555f1efd1969.png)
你好，在rec.py中，预测点击概率 选择了score的0位置处数值，如果跟标签值点击为1未点击为0对应，是不是选择1处位置处数据更符合直觉？可以这样理解吗：选择score的0位置处数值还是1位置处数据都无关紧要，只与人为习惯有关？

**Comment by Jhin3433** [comment]
你好，在rec.py中，预测点击概率 y_pred选择了score的0位置处数值，如果跟标签值点击为1未点击为0对应，是不是选择1处位置处数据更符合直觉？可以这样理解吗：选择score的0位置处数值还是1位置处数据都无关紧要，只与人为习惯有关。
![image](https://user-images.githubusercontent.com/33836571/126425082-e02c3de3-391c-43dc-924d-43d9bf4aa653.png)

**Comment by qinjr** [comment]
这个并不影响，我们就认为0的位置代表点击的概率 1的位置代表不点击的概率就好了

**Comment by Jhin3433** [comment]
![image](https://user-images.githubusercontent.com/33836571/126637245-734d0dbc-15fb-4899-8d24-2213e1fa4c44.png)
再次打扰，请问公式中这两步是怎么计算的，为什么下步比上步多了个一个log...
