### ISSUE TITLE
复现您的代码出现了一些问题，希望您能给予帮助，万分感谢

### ISSUE THREAD

**Issue by edge0001** [qinjr/UBR4CTR#5]
我在运行preprocessing_alipay.py的时候，代码出现了如下的报错FileNotFoundError: [Errno 2] No such file or directory: '../ubr4rec-data/alipay/feateng_data/id_remap_dict.pkl'。请问这个缺失的id_remap_dict.pkl文件，是怎么样得到的？希望您能在百忙之中解答一下。

**Comment by qinjr** [comment]
通过feateng这个函数，这一步就是在对原始feature做重新映射

**Comment by edge0001** [comment]
谢谢您的解答
