### ISSUE TITLE
复现您的代码的时候，出现了一个问题，希望您能在百忙之中抽空解答，非常感谢

### ISSUE THREAD

**Issue by edge0001** [qinjr/UBR4CTR#6]
不好意思打扰您了
我在运行preprocess_tmall.py文件的时候报错，具体报错如下
  File "G:/UBR4CTR/code/preprocess_tmall.py", line 301, in <module>
    feateng(FEATENG_DIR + 'joined_user_behavior.csv', FEATENG_DIR + 'remap_dict.pkl', FEATENG_DIR + 'time_distri.png', FEATENG_DIR + 'user_feat_dict.pkl', FEATENG_DIR + 'item_feat_dict.pkl')
TypeError: feateng() takes 4 positional arguments but 5 were given
为什么在源码中feateng()定义的时候有4个参数，但是在调用的时候却传入了5个参数，希望您能给予解答。万分感谢。

**Comment by qinjr** [comment]
sorry, fixed

**Comment by edge0001** [comment]
感谢您的解答。

**Comment by edge0001** [comment]
另外还有一处错误是这样的
Traceback (most recent call last):
  File "/home/lgb/论文代码/UBR4CTR/code/preprocess_tmall.py", line 307, in <module>
    insert_elastic(FEATENG_DIR + 'database.txt')
NameError: name 'insert_elastic' is not defined
我好像在preprocess_tmall.py文件中，没有找到相关函数的定义，希望您能解答一下这个问题。

**Comment by edge0001** [comment]
我在preprocess_taobao.py文件中找到相关的函数了，不好意思打扰您了
